### ISSUE TITLE
ERROR: "ragout-overlap" native module not found

### ISSUE THREAD

**Issue by anubhabkhan** [fenderglass/Ragout#13]
Hi, I tried to execute ragout but I am getting the following error:

INFO: Starting Ragout v1.2
[19:21:48] ERROR: "ragout-overlap" native module not found
[19:21:48] ERROR: An error occured while running Ragout:
[19:21:48] ERROR: overlap binary is missing, did you run 'make'?

I had run make. I am not able to solve this error. Could you please help?

**Comment by fenderglass** [comment]
Hi,

It seems that the binaries are missing. Could you run 'make clean && make' and post the output here?

**Comment by anubhabkhan** [comment]
Hi,

Thanks for replying:
This is the input and the output:
make clean && make
make -C ragout/overlap/cpp_impl clean
make[1]: Entering directory `~/ragout-1.2-linux-x86_64/ragout/overlap/cpp_impl'
rm *.o
rm ~/ragout-1.2-linux-x86_64/lib/ragout-overlap
rm: cannot remove `~/ragout-1.2-linux-x86_64/lib/ragout-overlap': No such file or directory
make[1]: *** [clean] Error 1
make[1]: Leaving directory `~/ragout-1.2-linux-x86_64/ragout/overlap/cpp_impl'
make: *** [clean] Error 2

**Comment by anubhabkhan** [comment]
I think it was an issue with my gcc version. It is working fine now after updating.
However, I get the error:
[16:36:46] INFO: Starting Ragout v1.2
[16:36:46] ERROR: An error occured while running Ragout:
[16:36:46] ERROR: Unknown recipe parameter 'fa' on line 3

my recipe file:
.references = reference
.target = genome

genome.fa = filepath/genome.fa
reference.fna = file_path/reference.fna

**Comment by fenderglass** [comment]
I'm glad that compilation now works!

For this error - you need to change "reference.fna" to "reference.fasta" to make it work.

**Comment by anubhabkhan** [comment]
Hi,
I am still getting the same error. I have changed the extension of the files from fna to fasta. Does the recipe file need more parameters?

thanks

**Comment by fenderglass** [comment]
No, no other parameters are required. Somehow I could not get this error with your settings. Could you attach the actual recipe file here and also provide the exact command line you are using?

**Comment by fenderglass** [comment]
Do you happen to have a dot symbol in the genomes names? I think this might cause issues.

**Comment by anubhabkhan** [comment]
Hi,

Thanks for replying so promptly. I am unable to attach the .rcp file as it is not supported here. But here is the content:

.references = GCA_000181335.3_Felis_catus_8.0
.target = genome

genome.fasta = /path/genome.fasta
GCA_000181335.3_Felis_catus_8.0.fasta = /extstor/anubhabk/GCA_000181335.3_Felis_catus_8.0/GCA_000181335.3_Felis_catus_8.0.fasta


Command line:
python2.7 /extstor/anubhabk/AKU_WORKING_DIRECTORY/SOFTWARES/ragout-1.2-linux-x86_64/ragout.py /extstor/anubhabk/genome/ragout/ragout.rcp --outdir /extstor/anubhabk/genome/ragout

**Comment by anubhabkhan** [comment]
Hi Mikhail,

I was not able to attach the files. Here is an attempt to mail them to you.

thanks a lot for helping me with this.


With regards and yours sincerely

Anubhab
Research Scholar,
National Centre for Biological Sciences,
Tata Institute of Fundamental Research,
India

**Comment by fenderglass** [comment]
Hi,
Seems that the genomes are too big to be processed with SIbelia - you will need to use Progressive Cactus instead. Please refer to the manual how to proceed and let me know if you have any extra questions.
