### ISSUE TITLE
Verify ragout2 assembly

### ISSUE THREAD

**Issue by xingwu2** [fenderglass/Ragout#17]
Hello,

I used Sibelia + ragout2 to reconstruct one of the soybean chromosome (Chr18) in my special soybean genotype (DS), and it worked very well. I tried to set the block scale as 'large' and 'small' to test it. In both ways, the program complained about the synteny blocks coverage (46.58%) is too low. However, both 'large' and 'small' returned very good results. Should I worry about the results? I wonder if there is a way to verify the accuracy of the assembly? What do you mean by the "true" reference for the verify-order.py? A DS genome assembly? I attached the log file for the two runs. 

[ragout_large.txt](https://github.com/fenderglass/Ragout/files/712229/ragout_large.txt)
[ragout_small.txt](https://github.com/fenderglass/Ragout/files/712231/ragout_small.txt)

Thanks!

Xing Wu

**Comment by fenderglass** [comment]
Hi,

Sorry for the late response. I am glad that the soybean assembly worked well. 46% synteny block coverage most likely means that the reference genome is distant from the target. In some cases it might result into assemblies of a low coverage, but as long as you are getting meaningful results (high coverage, low fragmentation), it should be fine. Generally, Progressive Cactus alignment should do a better job on divergent genomes, as it does not require them to share many long k-mers.

There is no "general" way to check the accuracy, usually we use some extra outside information, like transcripts or chromosome maps. "True" reference in the script means the actual complete target genome - the script was designed for benchmarking via simulations, so it does not apply for your case.

Best,
Mikhail

**Comment by xingwu2** [comment]
Hi Mikhail,

Thank you for the detailed reply. 

The soybean genotype I sequenced and the reference are the same species, although one is US cultivar, the other one is Brazilian cultivar. They should not be very distant. 

Since no matter I chose 'small' or 'large' for the block scale, the program kept complaining about the synteny block, shall I just ignore this warning message and go with the 'large' block scale because it did a better job in term of N50. Keeping in mind that the program automatically choose 'small' for the block size, and the program only complained once. As for the 'large' block, the program complained twice. 

How would you choose the block scale?

I tried to install and run Progressive Cactus on the cluster but there are some system issues. I am still trying to debug, but if I fail to do that, do you mind helping us run the Progressive Cactus from your side (sort of collaboration)? 

Best

Xing Wu
Graduate Student
Department of Crop Sciences
University of Illinois at Urbana-Champaign

**Comment by fenderglass** [comment]
Hi Xing,

Sure, you can use "large" scale if it works better for you, I think it's a more reasonable choice for a eukaryotic genome. 

What it the expected sequence divergence between to species? Sibelia currently has limitations when the genomes do not have enough shared k-mers.

Sure, let me know if you have issues with Cactus. The package is under active development now, so the installation process might be challenging on some configurations. You can also write me directly at fenderglass@gmail.com.

Best,
Mikhail
