### ISSUE TITLE
Sibelia not running multi-threads with -t or --threads option

### ISSUE THREAD

**Issue by stsmall** [fenderglass/Ragout#2]
when I run the command line: "ragout.py -o ragout_contigs -s sibelia --threads 20 wbcontig.rcp"
Sibelia starts but only a single thread is used. There are no errors associated with compilation or runtime.
Any ideas?

**Comment by fenderglass** [comment]
That's right, --threads option is yet limited to HAL backend. This would be fixed in near future.
However, the expected speedup is about 3x (number of iterations) as Sibelia itself is not parallel.
