### ISSUE TITLE
Ragout with HAL input

### ISSUE THREAD

**Issue by stephenrdoyle** [fenderglass/Ragout#21]
Hi, 

Just wondering if you have any example datasets / recipe files available for which you used a HAL file as input? Just trying to troubleshoot.

Best
Steve

**Comment by fenderglass** [comment]
Sure, here is an example.
[hal_example.tar.gz](https://github.com/fenderglass/Ragout/files/1167683/hal_example.tar.gz)

Let me know if you have more questions - you can write directly to fenderglass@gmail.com

**Comment by jennomics** [comment]
Hi! Thanks for providing the example files. I'm unable to get ragout to run using them. 

I am running this, from within the hal_example directory:

 **/home/ubuntu/software/ragout-2.0-linux-x86_64/ragout.py cholerae.rcp -o example_out --refine --overwrite --threads 60**

here's the error message:

**[20:54:55] INFO: Starting Ragout v2.0
[20:54:55] ERROR: An error occured while running Ragout:
[20:54:55] ERROR: Could not open target FASTA file or it is not specified**

I am able to run halStats on the alignment, so I know HAL tools are working.

I'm running this on an AWS ubuntu instance, r4.16xlarge.

I appreciate your help in troubleshooting this!

**Comment by fenderglass** [comment]
You need to add '-s hal' option.

**Comment by jennomics** [comment]
thank you - it's working now. I figured I was overlooking something like that. appreciate the help!
