### ISSUE TITLE
setup.py install --prefix=XXXX does not install necessary modules

### ISSUE THREAD

**Issue by EricDeveaud** [fenderglass/Ragout#39]
Hello, 

after issuing the following command 
```sh
python setup.py install --prefix=/some/path
```
and test of ```ragout -h```

I had to perform some modifications to the installation and to the main ragout python scripts in order to have the third party modules (networkx and  newick) found 

1) modules from the lib directory are not installed 
2) ragout main script expect ```lib``` at the same level than ```bin```. 
usally helper modules must go the $PREFIX/lib/python2.7/site-packages, so ragout could not find his helper modules 

so to fix the installation I had to 
1) manual copy ```$SRC/lib/networkx``` and ```$SRC/lib/newick``` to ```/some/path/lib/python2.7/site-packages``` 
2) hack ragout to use the correct location before installation
```sed -i -e "s|^lib_absolute.*|lib_absolute='newick'|" bin/ragout```

also ```sys.path.insert(0, ragout_root)``` is useless as there is no python modules that can be imported from this location

regards 

Eric

**Comment by fenderglass** [comment]
Hello,

`lib` directory is only used for running Ragout locally without installation. For system integration, you should manually install the dependencies (newick and networkx) and make sure they go into the same prefix (or just use bioconda).
