### ISSUE TITLE
ERROR: "hal" is not installed.

### ISSUE THREAD

**Issue by shameem356** [fenderglass/Ragout#45]
Hello Team & @fenderglass  
I tried to run ragout with hal option. But I am getting the following error. I have properly installed hal software and added the PATH and PYTHONPTH in ~/.bashrc file.

**Ragout command** : bin/ragout -s hal --refine hal_example/hal_example/cholerae.rcp -o out 

**PATH setting command in bashrc**
export PYTHONPATH=/data/labs/genomics_lab/shared/apps/HAL/hal/:$PYTHONPATH
export PATH=/data/labs/genomics_lab/shared/apps/HAL/hal/bin/:$PATH

**Error Message :**

[15:56:26] INFO: Starting Ragout v2.2
[15:56:26] ERROR: An error occured while running Ragout:
[15:56:26] ERROR: "hal" is not installed. 

Please can you let me know how to solve this issue.

**Comment by fenderglass** [comment]
Hi,

Looks like Ragout can't find hal executables. Maybe your .bashrc was not loaded? Please check the output of `which halStats` and also `echo $PATH` to make sure the environment was loaded properly. You can also apply `export` commands directly into the current bash session to check if it's working properly.

Best,
Mikhail

**Comment by shameem356** [comment]
Hello @fenderglass ,

I checked .bashrc file and it is loaded properly . I checked  **which halStats** and also **echo $PATH** after getting the "hal  is not installed" error message (See below).And still the problem remain.I have the following list of [hal executable files]( https://wcmq.box.com/s/tr6zdfq3ie5r034a6yq1mcrtie7q98x4 ) in my PATH.Please let me know if I missed any hal executable file which causing the error 

Hal Executable file :

 **Ragout]$ bin/ragout -s hal --refine hal_example/hal_example/cholerae.rcp -o out**
[09:56:58] INFO: Starting Ragout v2.2
[09:56:58] ERROR: An error occured while running Ragout:
[09:56:58] ERROR: "hal" is not installed.

 **which halStats**
/data/labs/genomics_lab/shared/apps/HAL/hal/bin/halStats

**echo $PATH**
/data/labs/genomics_lab/shared/apps/HAL/hal/bin:/data/apps/software/perl-5.26.0/site/bin:/data/apps/software/perl-5.26.0/bin:/data/apps/software/R-3.4.4/bin/Rscript:/data/apps/software/R-3.4.4/bin:/data/apps/software/java/jdk1.8.0_191/bin:/data/apps/software/samtools-1.3/bin:/data/labs/genomics_lab/shared/apps/hdf5-1.10.1/hdf5/bin:/opt/advcomp/bin:/usr/lib64/openmpi/bin:/usr/lib64/nagios/plugins:/usr/lpp/mmfs/bin:/opt/bin:/opt/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/data/labs/genomics_lab/shared/shameem/apps/php-5.6/sapi/cli

**Comment by fenderglass** [comment]
Thank you! It seems that `halStats` and `hal2fasta` are indeed in your PATH. Could you also double check they are executable by invoking them? (sometimes file permissions could be messed up).

Also, I don't see `hal2mafMP.py` script in your PATH - I think this might be the issue. I think it should be placed in the `hal/bin` directory, but maybe the location has changed in the recent HAL releases? Which version are you using?

**Comment by shameem356** [comment]
I tried with HAL V2.1 and V2.0. Both are having same problem. Please can you check the ragout running status with these versions of HAL.OR please let me know which HAL version will be suitable of Ragout ?

**Comment by fenderglass** [comment]
I am using HAL 2.1.

Please double check that hal is properly installed by invoking `halStats`, `hal2fasta` and `hal2mafMP.py` commands and post the output of all three commands here.

**Comment by shameem356** [comment]
solved the file. Actual problem was related to hal2mafMP.py. In HAL installation  , hal2mafMP.py was located in maf folder. I copied  hal2mafMP.py file to bin folder from maf and it solved the problem.

@fenderglass : Thank you so much your time and quick helps.
