### ISSUE TITLE
Lowering the minimum size for sinteny blocks

### ISSUE THREAD

**Issue by salvocamiolo** [fenderglass/Ragout#48]
Dear Authors,

I used Ragout on some viral genome and the analysis was very successful. However I can not use Ragout on all the viruses I usually work with because the minimum sequence size to be considered in the synteny blocks is 5000 bp. Several viruses feature a genomic size of less than 10,000 bp and somtimes segments of 1000 bp or less. Do you think that you may release a version of the software that can handle such short genomes. That would be interesting to test to see whether the promising results I obtained so for on bigger viruses can confirmed on smaller ones. 
Thanks a lot for you support

**Comment by fenderglass** [comment]
Hi,

Thanks for the feedback!

Sure, you can use custom synteny block size as described here: https://github.com/fenderglass/Ragout/blob/master/docs/USAGE.md#synteny-block-scale

**Comment by salvocamiolo** [comment]
Hi Mickhail,

thanks for your message. Sorry about that, I actually hadn't seen this part of the manual. Everything was sorted out according to your suggestion
best regards
Salvo


Il 10 lug 2019, 02:46 +0200, Mikhail Kolmogorov <notifications@github.com>, ha scritto:
