### ISSUE TITLE
Why is my scaffolded genome larger than the total contig length and my target genome?

### ISSUE THREAD

**Issue by CristianRiccio** [fenderglass/Ragout#49]
Hi,
I have run Ragout with default parameters between a set of contigs (file size 92 M), and a chromosome-length reference genome (99 M) and obtained a gap-free genome of 101 M. How is that possible? I thought Ragout would just order the contigs based on the reference and put Ns in the gaps.
Cheers.

**Comment by fenderglass** [comment]
It is possible because Ragout inserts gaps (sequence of Ns) between the scaffolded contigs. It outputs the number of inserted Ns into the log file + you can check .links and / or .agp files to see where the gaps are.
