### ISSUE TITLE
Comparing variants detecting from Ragout genome and other variant calling tools

### ISSUE THREAD

**Issue by sf-nevermore** [fenderglass/Ragout#50]
Hi,

I want to study SNPs and InDels of several regions among mice strains. I am think of 2 approach. One is to look up the aligned regions of the strain's genome from Ragout post (https://zenodo.org/record/1408270#.XUo_s5NKjUI). The other one is to work with the VCF file recording the SNPs and InDel data. As far as I know variant calling and Ragout genome assemble both reference based. I am confused of the connection and the differences of variants detection between these approaches?

Thank you very much for your help.

**Comment by fenderglass** [comment]
Hi,

Ragout uses reference genome to scaffold target contigs, but does not reveal variants between the genomes. You will need a different tool to reveal variants, such as whole genome alignment using Cactus (https://github.com/ComparativeGenomicsToolkit/cactus) or SibeliaZ (https://github.com/medvedevgroup/SibeliaZ)

Hope this helps,
Mikhail
