### ISSUE TITLE
Cannot install following procedure

### ISSUE THREAD

**Issue by enormandeau** [fenderglass/Ragout#56]
I installed toil on my system (had to compile) and followed the ragout installation procedure at:

https://github.com/fenderglass/Ragout/blob/master/docs/INSTALL.md

I get the following last lines will trying to use make:
```
make[3]: Leaving directory '/home/eric/Desktop/coelopa_ragout/cactus/submodules/cPecan/externalTools'                                                          
make[2]: Leaving directory '/home/eric/Desktop/coelopa_ragout/cactus/submodules/cPecan'                                                                        
make[1]: Leaving directory '/home/eric/Desktop/coelopa_ragout/cactus'                                                                                          
Makefile:32: recipe for target 'all' failed                                                                                                                    
make: *** [all] Error 2
```

At this point, using python3, is there an easy way to install Ragout?

**Comment by fenderglass** [comment]
Hi,

This looks like a a part the Progressive Cactus build log, not Ragout. If you have issue building Cactus, please refer to the corresponding repository to get help: https://github.com/ComparativeGenomicsToolkit/cactus

If you are having issue building Ragout, please post the full build log with error (not just the last few lines), or alternatively use the bioconda package.

Mikhail
