### ISSUE TITLE
Input is larger than 1 GB, can't proceed

### ISSUE THREAD

**Issue by fergsc** [fenderglass/Ragout#58]
Hi, I have assembled 21 plant genomes of ~600mbp and would like to use Ragout to scaffold them. I have sucessfully run sibeliaZ on my genomes and produced a maf file of 14G. When I try to run Ragout I get the error ```error: Input is larger than 1 GB, can't proceed```. Is there a hard limit on the input data size for Ragout and if so is there a way around this issue?

thanks

**Comment by fenderglass** [comment]
@fergsc SibeliaZ has not yet been integrated into Ragout. The original Sibelia can't handle input that large. The current solution is to use progressive cactus alignment. I also would recommend to select 4-5 closest references instead of using all 21.

Mikhail

**Comment by fergsc** [comment]
Thanks for the quick response.

Based on this https://github.com/fenderglass/Ragout/issues/40 I thought sibeliaZ was capable of being used with ragout. I shall try and convert my maf into a hal and see how it goes. Running Cactus in my HPC is hard/not possible. Was really hping to use Ragout, all my genomes are very closly related and have a lot of shared synteny.

Thanks again.
