### ISSUE TITLE
Ragout can read fasta files

### ISSUE THREAD

**Issue by JessicaCruz31** [fenderglass/Ragout#7]
hi! I'm kind of a newbie, so maybe this is a silly problem, but I will ask anyway:
I made the recipe file-.target = BacaeroM

BTT.fasta = references/BTT.fasta
BTT2.fasta = references/BTT2.fasta
BTo.fasta = references/BTo.fasta
BacaeroM.fasta = BacaeroM.fasta

but after running the program I get this:
[10:47:39] root: INFO: Starting Ragout v1.2
[10:47:39] root: ERROR: An error occured while running Ragout
[10:47:39] root: ERROR: Could not open target FASTA file or it is not specified

Maybe its the path that has something missing, maybe not.
Can anybody help?

**Comment by fenderglass** [comment]
Hi!
Looks like it can not find the fasta file with assembly. Is it in the same directory with the recipe file?

**Comment by JessicaCruz31** [comment]
Yes, the files are in the same directory, and yet it gives me the same error.
What else can it be?

**Comment by fenderglass** [comment]
This looks strange. 
Do provided examples work for you? Could you also paste the recipe file in full (in one that you posted previously there is at least ".references" parameter missing)?
