### ISSUE TITLE
Unable to run Ragout

### ISSUE THREAD

**Issue by sunnyEV** [fenderglass/Ragout#77]
I provided all the necessary files, 
1. Config-file 
  REF col=Clump.fa
  TARGET usa=Aventine-scaffolds.abyss.CDHIT.fa
  BLOCK=5000,500,100

When I submit the job. I'm facing this issue.  Some help, needed.

> [19:55:38] INFO: Starting Ragout v2.3
> [19:55:38] ERROR: An error occurred while running Ragout:
> [19:55:38] ERROR: Error parsing recipe on line 1

**Comment by fenderglass** [comment]
You recipe file has incorrect syntax - please refer to the manual for the examples.
