### ISSUE TITLE
add option for not breaking input scaffold?

### ISSUE THREAD

**Issue by yjx1217** [fenderglass/Ragout#8]
Hello, I was trying to use ragout to re-ordering and re-orientating my existing scaffolds based on the reference chromosome order. I think ragout generally did a good job for most cases but there are some cases that my assembled genome is known to have many species-specific genome re-arrangements, for which the current ragout will incorrectly interpret them as assembly errors and try to break the existing scaffolds and completely re-organize them based on the reference genome. So I was wondering if you can add an option to let ragout just do the scaffold re-ordering and re-orientating but not break existing scaffolds. Say if scaffold1 matches part of chr3 and part of chr4, ragout will just label it as chr_chr3_chr4 and log the breakpoint information.  It will be great if this option can be implemented.

Another minor suggestion is to let ragout to output the post-processed assembly based on reference's chromosome order. So the final output will contains scaffolds named as chr_chr1, chr_chr2, chr_chr3 ... 

Thanks in advance!

**Comment by fenderglass** [comment]
Hello,

1. This looks like a good suggestion. I can add an option to completely turn off the misassembly detection module.

2. Do I understand correctly, you want the output to be sorted according to the chromosome order in the reference genome? That is a good point as well, that should be pretty easy to implement.

Thanks for the good suggestions!

**Comment by yjx1217** [comment]
Hi Mikhail,

"Do I understand correctly, you want the output to be sorted according to
the chromosome order in the reference genome? That is a good point as well,
that should be pretty easy to implement."

> Yes, this is what I mean.

Thanks for the consideration and looks forward to the new version.

Best,
Jia-Xing

**Comment by fenderglass** [comment]
Hi Jia-Xing,

I added support for both of your suggestions, they are currently in the master branch.

**Comment by yjx1217** [comment]
Thank you very much, Mikhail!

Best,
Jia-Xing

On Wed, Feb 17, 2016 at 9:51 PM, Mikhail Kolmogorov <
notifications@github.com> wrote:

> Hi Jia-Xing,
>
> I added support for both of your suggestions, they are currently in the
> master branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fenderglass/Ragout/issues/8#issuecomment-185397637>.
>



-- 
Jia-Xing Yue

Population Genomics and Complex Traits Group
Tour Pasteur 8eme etage
Faculté de Médecine
Institute for Research on Cancer and Aging, Nice (IRCAN)
CNRS UMR 7284 - INSERM U 1081
Université de Nice Sophia Antipolis
28 Avenue de Valombrose
06107 NICE Cedex 2
France

Lab website: http://ircan.org/index.php?Itemid=98
Personal website: http://www.iamphioxus.org/
