### ISSUE TITLE
Does Ragout trim contigs' ends?

### ISSUE THREAD

**Issue by touala** [fenderglass/Ragout#87]
Hello @fenderglass and team,

Thanks for developping this nice tool.

I have a couple yeast assemblies produced with `canu` with generally nice contiguity, one contig per chromosome. However, for some assembled chromosomes end up splitted into two contigs. Long read coverage clearly indicates that matching ends are composed of duplicated sequences (up to 50 kbp) but `ragout` scaffolding do not resolved the duplication and concatenate them with Ns.

Does Ragout generally trims contigs ends when scaffolding indicate duplication? Is there a maximum duplicated length that it can handle? Any pointers are welcome.

Best,

Alan

**Comment by fenderglass** [comment]
Hi Alan,

Ragout in general does not change contig sequences. It may split a contig into parts if it thinks it's chimeric, but it was not designed to trim duplications.

**Comment by touala** [comment]
Thanks for the quick answer. Best.
